### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by RyDroid** [mikangali-labs/mediawiki_ynh#6]
What is the license? Is it a free/libre one?

**Comment by ElieSauveterre** [comment]
Yes it's free, no restrictions :)

**Comment by RyDroid** [comment]
[Creative Commons 0 v1.0](https://creativecommons.org/publicdomain/zero/1.0/)?

**Comment by ElieSauveterre** [comment]
No, this one => [Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)?
